# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'iot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiot.proto\"3\n\x08Registro\x12\r\n\x05porta\x18\x01 \x01(\x05\x12\x18\n\x10tipo_dispositivo\x18\x02 \x01(\t\"=\n\x05\x44\x61\x64os\x12\r\n\x05valor\x18\x01 \x01(\x02\x12\x0f\n\x07unidade\x18\x02 \x01(\t\x12\x14\n\x0ctipo_leitura\x18\x03 \x01(\t\"&\n\x07\x43omando\x12\x0c\n\x04\x61\x63\x61o\x18\x01 \x01(\t\x12\r\n\x05param\x18\x02 \x01(\t\"\x83\x01\n\x08Mensagem\x12\x11\n\tid_origem\x18\x01 \x01(\t\x12\x15\n\rtipo_mensagem\x18\x02 \x01(\t\x12\x1b\n\x08registro\x18\x03 \x01(\x0b\x32\t.Registro\x12\x15\n\x05\x64\x61\x64os\x18\x04 \x01(\x0b\x32\x06.Dados\x12\x19\n\x07\x63omando\x18\x05 \x01(\x0b\x32\x08.Comandob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRO']._serialized_start=13
  _globals['_REGISTRO']._serialized_end=64
  _globals['_DADOS']._serialized_start=66
  _globals['_DADOS']._serialized_end=127
  _globals['_COMANDO']._serialized_start=129
  _globals['_COMANDO']._serialized_end=167
  _globals['_MENSAGEM']._serialized_start=170
  _globals['_MENSAGEM']._serialized_end=301
# @@protoc_insertion_point(module_scope)
